### ISSUE TITLE
Turbidity data for MPA refers to ACA data location?

### ISSUE THREAD

**Issue by ConnectedSystems** [ConnectedSystems/GBR-Bathy10m#23]
At [this point](https://github.com/open-AIMS/GBR-reef-guidance-assessment/blob/1c3d1464df2e1adfa7b5b31c0502fa84d3ed5dad/src/1a_prep_MPA.jl#L154) in the data preprocessing step, the script attempts to load turbidity data.

There are two issues:

1. The turbidity source data is not made available (the file is missing?)
2. The data source location referred to in the script (1a) is the **ACA processing output** directory. This is not aligned with the Step 1a, which processes **MPA data**.

It appears it is indeed created in [script 1b](https://github.com/open-AIMS/GBR-reef-guidance-assessment/blob/1c3d1464df2e1adfa7b5b31c0502fa84d3ed5dad/src/1b_prep_aca.jl#L94), but how is it supposed to exist in Step 1a, if it is created in Step 1b?

Pinging @BG-AIMS

**Comment by eco-ben** [comment]
Yes, I will change the turbidity lines in 1a so it accesses the raw turbidity data from ACA_DATA_DIR and processes it in the same way 1b does so 1a doesn't have to access output from 1b.

**Comment by ConnectedSystems** [comment]
Looks like the change was made 2 weeks ago, and merged in by me a few days ago (#21).

So my fault for doing a cursory review.
